# ============================================================
# MODULE ÉQUIPEMENTS
# Base de données : panneaux, batteries, régulateurs, onduleurs
# Source : Base de données réelles (Victron, Jinko, BAE, etc.)
# ============================================================


# ============================================================
# BASE DE DONNÉES DES PANNEAUX SOLAIRES
# ============================================================

PANNEAUX = [
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 20.0,
        "tension_V":   12.0,
        "Vmp_V":       18.4,
        "Imp_A":       1.09,
        "Voc_V":       21.96,
        "Isc_A":       1.18,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 30.0,
        "tension_V":   12.0,
        "Vmp_V":       18.2,
        "Imp_A":       1.66,
        "Voc_V":       21.8,
        "Isc_A":       1.8,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 45.0,
        "tension_V":   12.0,
        "Vmp_V":       19.1,
        "Imp_A":       2.36,
        "Voc_V":       22.9,
        "Isc_A":       2.55,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 50.0,
        "tension_V":   12.0,
        "Vmp_V":       18.0,
        "Imp_A":       2.78,
        "Voc_V":       22.2,
        "Isc_A":       3.09,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 60.0,
        "tension_V":   12.0,
        "Vmp_V":       19.3,
        "Imp_A":       3.12,
        "Voc_V":       23.1,
        "Isc_A":       3.37,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 80.0,
        "tension_V":   12.0,
        "Vmp_V":       18.0,
        "Imp_A":       4.44,
        "Voc_V":       21.6,
        "Isc_A":       5.06,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 90.0,
        "tension_V":   12.0,
        "Vmp_V":       19.5,
        "Imp_A":       4.61,
        "Voc_V":       23.44,
        "Isc_A":       4.98,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 100.0,
        "tension_V":   12.0,
        "Vmp_V":       18.0,
        "Imp_A":       5.56,
        "Voc_V":       21.6,
        "Isc_A":       6.32,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 115.0,
        "tension_V":   12.0,
        "Vmp_V":       18.9,
        "Imp_A":       6.08,
        "Voc_V":       22.73,
        "Isc_A":       6.56,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 140.0,
        "tension_V":   12.0,
        "Vmp_V":       20.0,
        "Imp_A":       7.78,
        "Voc_V":       21.6,
        "Isc_A":       8.85,
        "rendement":   0.005,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 175.0,
        "tension_V":   12.0,
        "Vmp_V":       18.3,
        "Imp_A":       9.56,
        "Voc_V":       21.9,
        "Isc_A":       10.24,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 250.0,
        "tension_V":   24.0,
        "Vmp_V":       30.0,
        "Imp_A":       8.33,
        "Voc_V":       36.75,
        "Isc_A":       8.94,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 270.0,
        "tension_V":   24.0,
        "Vmp_V":       31.7,
        "Imp_A":       8.52,
        "Voc_V":       38.04,
        "Isc_A":       9.21,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 290.0,
        "tension_V":   24.0,
        "Vmp_V":       36.0,
        "Imp_A":       8.06,
        "Voc_V":       44.1,
        "Isc_A":       8.56,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 330.0,
        "tension_V":   24.0,
        "Vmp_V":       37.3,
        "Imp_A":       8.86,
        "Voc_V":       44.72,
        "Isc_A":       9.57,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Polycristallin",
        "puissance_W": 360.0,
        "tension_V":   24.0,
        "Vmp_V":       38.4,
        "Imp_A":       9.38,
        "Voc_V":       47.4,
        "Isc_A":       10.24,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Monocristallin",
        "puissance_W": 160.0,
        "tension_V":   12.0,
        "Vmp_V":       18.0,
        "Imp_A":       8.9,
        "Voc_V":       22.4,
        "Isc_A":       9.9,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Monocristallin",
        "puissance_W": 200.0,
        "tension_V":   24.0,
        "Vmp_V":       36.0,
        "Imp_A":       5.55,
        "Voc_V":       43.2,
        "Isc_A":       6.1,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Monocristallin",
        "puissance_W": 305.0,
        "tension_V":   24.0,
        "Vmp_V":       32.5,
        "Imp_A":       9.38,
        "Voc_V":       39.7,
        "Isc_A":       10.27,
        "rendement":   0.006,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Monocristallin",
        "puissance_W": 340.0,
        "tension_V":   24.0,
        "Vmp_V":       36.0,
        "Imp_A":       9.44,
        "Voc_V":       45.5,
        "Isc_A":       10.3,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 275.0,
        "tension_V":   24.0,
        "Vmp_V":       32.2,
        "Imp_A":       8.54,
        "Voc_V":       38.8,
        "Isc_A":       8.92,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 270.0,
        "tension_V":   24.0,
        "Vmp_V":       31.9,
        "Imp_A":       8.45,
        "Voc_V":       38.6,
        "Isc_A":       8.89,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 265.0,
        "tension_V":   24.0,
        "Vmp_V":       31.7,
        "Imp_A":       8.36,
        "Voc_V":       38.4,
        "Isc_A":       8.85,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 260.0,
        "tension_V":   24.0,
        "Vmp_V":       30.8,
        "Imp_A":       8.45,
        "Voc_V":       38.0,
        "Isc_A":       8.83,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 255.0,
        "tension_V":   24.0,
        "Vmp_V":       30.6,
        "Imp_A":       8.33,
        "Voc_V":       37.8,
        "Isc_A":       8.74,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 250.0,
        "tension_V":   24.0,
        "Vmp_V":       30.5,
        "Imp_A":       8.21,
        "Voc_V":       37.6,
        "Isc_A":       8.67,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 165.0,
        "tension_V":   12.0,
        "Vmp_V":       18.2,
        "Imp_A":       9.06,
        "Voc_V":       22.3,
        "Isc_A":       9.74,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 160.0,
        "tension_V":   12.0,
        "Vmp_V":       18.1,
        "Imp_A":       8.84,
        "Voc_V":       22.1,
        "Isc_A":       9.53,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 150.0,
        "tension_V":   12.0,
        "Vmp_V":       17.9,
        "Imp_A":       8.38,
        "Voc_V":       21.9,
        "Isc_A":       9.01,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 145.0,
        "tension_V":   12.0,
        "Vmp_V":       18.8,
        "Imp_A":       8.15,
        "Voc_V":       21.8,
        "Isc_A":       8.75,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 140.0,
        "tension_V":   12.0,
        "Vmp_V":       17.7,
        "Imp_A":       7.92,
        "Voc_V":       21.7,
        "Isc_A":       8.49,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 135.0,
        "tension_V":   12.0,
        "Vmp_V":       17.6,
        "Imp_A":       7.68,
        "Voc_V":       21.6,
        "Isc_A":       8.33,
        "rendement":   0.006,
    },
    {
        "marque":      "Hiteck Qindao",
        "type":        "Polycristallin",
        "puissance_W": 130.0,
        "tension_V":   12.0,
        "Vmp_V":       17.5,
        "Imp_A":       7.43,
        "Voc_V":       21.5,
        "Isc_A":       7.96,
        "rendement":   0.006,
    },
    {
        "marque":      "Alex Solar",
        "type":        "Poycristallin",
        "puissance_W": 245.0,
        "tension_V":   24.0,
        "Vmp_V":       31.1,
        "Imp_A":       7.88,
        "Voc_V":       37.4,
        "Isc_A":       8.4,
        "rendement":   0.006,
    },
    {
        "marque":      "Alex Solar",
        "type":        "Poycristallin",
        "puissance_W": 250.0,
        "tension_V":   24.0,
        "Vmp_V":       31.4,
        "Imp_A":       7.96,
        "Voc_V":       37.6,
        "Isc_A":       8.45,
        "rendement":   0.006,
    },
    {
        "marque":      "Alex Solar",
        "type":        "Poycristallin",
        "puissance_W": 255.0,
        "tension_V":   24.0,
        "Vmp_V":       31.6,
        "Imp_A":       8.07,
        "Voc_V":       37.8,
        "Isc_A":       8.52,
        "rendement":   0.006,
    },
    {
        "marque":      "Alex Solar",
        "type":        "Poycristallin",
        "puissance_W": 260.0,
        "tension_V":   24.0,
        "Vmp_V":       31.9,
        "Imp_A":       8.15,
        "Voc_V":       38.0,
        "Isc_A":       8.58,
        "rendement":   0.006,
    },
    {
        "marque":      "Alex Solar",
        "type":        "Poycristallin",
        "puissance_W": 265.0,
        "tension_V":   24.0,
        "Vmp_V":       32.7,
        "Imp_A":       8.23,
        "Voc_V":       38.1,
        "Isc_A":       8.61,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Polycristallin",
        "puissance_W": 255.0,
        "tension_V":   24.0,
        "Vmp_V":       30.43,
        "Imp_A":       8.38,
        "Voc_V":       37.67,
        "Isc_A":       8.91,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Polycristallin",
        "puissance_W": 260.0,
        "tension_V":   24.0,
        "Vmp_V":       30.59,
        "Imp_A":       8.5,
        "Voc_V":       38.16,
        "Isc_A":       9.07,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Polycristallin",
        "puissance_W": 265.0,
        "tension_V":   24.0,
        "Vmp_V":       30.74,
        "Imp_A":       8.62,
        "Voc_V":       38.29,
        "Isc_A":       9.24,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Polycristallin",
        "puissance_W": 270.0,
        "tension_V":   24.0,
        "Vmp_V":       30.97,
        "Imp_A":       8.72,
        "Voc_V":       38.43,
        "Isc_A":       9.31,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Polycristallin",
        "puissance_W": 300.0,
        "tension_V":   24.0,
        "Vmp_V":       36.95,
        "Imp_A":       8.12,
        "Voc_V":       45.21,
        "Isc_A":       8.59,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Polycristallin",
        "puissance_W": 305.0,
        "tension_V":   24.0,
        "Vmp_V":       36.97,
        "Imp_A":       8.25,
        "Voc_V":       45.23,
        "Isc_A":       8.6,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Polycristallin",
        "puissance_W": 310.0,
        "tension_V":   24.0,
        "Vmp_V":       37.0,
        "Imp_A":       8.38,
        "Voc_V":       45.5,
        "Isc_A":       9.35,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Polycristallin",
        "puissance_W": 315.0,
        "tension_V":   24.0,
        "Vmp_V":       37.2,
        "Imp_A":       8.47,
        "Voc_V":       45.7,
        "Isc_A":       9.5,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Polycristallin",
        "puissance_W": 320.0,
        "tension_V":   24.0,
        "Vmp_V":       37.5,
        "Imp_A":       8.53,
        "Voc_V":       46.0,
        "Isc_A":       9.5,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Monocristallin",
        "puissance_W": 275.0,
        "tension_V":   24.0,
        "Vmp_V":       30.9,
        "Imp_A":       8.91,
        "Voc_V":       38.8,
        "Isc_A":       9.47,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Monocristallin",
        "puissance_W": 280.0,
        "tension_V":   24.0,
        "Vmp_V":       31.3,
        "Imp_A":       8.96,
        "Voc_V":       39.1,
        "Isc_A":       9.5,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Monocristallin",
        "puissance_W": 315.0,
        "tension_V":   36.0,
        "Vmp_V":       36.35,
        "Imp_A":       8.67,
        "Voc_V":       45.86,
        "Isc_A":       9.42,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Monocristallin",
        "puissance_W": 320.0,
        "tension_V":   36.0,
        "Vmp_V":       36.53,
        "Imp_A":       8.76,
        "Voc_V":       45.73,
        "Isc_A":       9.49,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Monocristallin",
        "puissance_W": 325.0,
        "tension_V":   36.0,
        "Vmp_V":       36.69,
        "Imp_A":       8.76,
        "Voc_V":       45.99,
        "Isc_A":       9.56,
        "rendement":   0.006,
    },
    {
        "marque":      "Innova Solarline",
        "type":        "Monocristallin",
        "puissance_W": 330.0,
        "tension_V":   36.0,
        "Vmp_V":       36.75,
        "Imp_A":       8.96,
        "Voc_V":       46.12,
        "Isc_A":       9.63,
        "rendement":   0.006,
    },
    {
        "marque":      "Solar world",
        "type":        "Polycristallin",
        "puissance_W": 150.0,
        "tension_V":   12.0,
        "Vmp_V":       18.3,
        "Imp_A":       8.27,
        "Voc_V":       22.5,
        "Isc_A":       8.81,
        "rendement":   0.006,
    },
    {
        "marque":      "Solar world",
        "type":        "Monocristallin",
        "puissance_W": 80.0,
        "tension_V":   12.0,
        "Vmp_V":       18.5,
        "Imp_A":       4.35,
        "Voc_V":       22.5,
        "Isc_A":       4.66,
        "rendement":   0.006,
    },
    {
        "marque":      "Solar world",
        "type":        "Monocristallin",
        "puissance_W": 290.0,
        "tension_V":   24.0,
        "Vmp_V":       31.9,
        "Imp_A":       9.2,
        "Voc_V":       39.6,
        "Isc_A":       9.75,
        "rendement":   0.006,
    },
    {
        "marque":      "Solar world",
        "type":        "Monocristallin",
        "puissance_W": 300.0,
        "tension_V":   24.0,
        "Vmp_V":       32.6,
        "Imp_A":       9.31,
        "Voc_V":       40.0,
        "Isc_A":       9.83,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Polycristallin",
        "puissance_W": 260.0,
        "tension_V":   24.0,
        "Vmp_V":       30.4,
        "Imp_A":       8.55,
        "Voc_V":       37.4,
        "Isc_A":       9.11,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Polycristallin",
        "puissance_W": 265.0,
        "tension_V":   24.0,
        "Vmp_V":       30.5,
        "Imp_A":       8.68,
        "Voc_V":       37.5,
        "Isc_A":       9.21,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Polycristallin",
        "puissance_W": 270.0,
        "tension_V":   24.0,
        "Vmp_V":       30.9,
        "Imp_A":       8.74,
        "Voc_V":       38.2,
        "Isc_A":       9.3,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Polycristallin",
        "puissance_W": 275.0,
        "tension_V":   24.0,
        "Vmp_V":       30.9,
        "Imp_A":       8.9,
        "Voc_V":       38.2,
        "Isc_A":       9.35,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Polycristallin",
        "puissance_W": 280.0,
        "tension_V":   24.0,
        "Vmp_V":       31.1,
        "Imp_A":       9.01,
        "Voc_V":       38.5,
        "Isc_A":       9.44,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Polycristallin",
        "puissance_W": 285.0,
        "tension_V":   24.0,
        "Vmp_V":       31.3,
        "Imp_A":       9.1,
        "Voc_V":       38.6,
        "Isc_A":       9.54,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Polycristallin",
        "puissance_W": 315.0,
        "tension_V":   36.0,
        "Vmp_V":       36.7,
        "Imp_A":       8.58,
        "Voc_V":       45.5,
        "Isc_A":       9.17,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Polycristallin",
        "puissance_W": 320.0,
        "tension_V":   36.0,
        "Vmp_V":       36.7,
        "Imp_A":       8.72,
        "Voc_V":       45.5,
        "Isc_A":       9.32,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Polycristallin",
        "puissance_W": 325.0,
        "tension_V":   36.0,
        "Vmp_V":       36.9,
        "Imp_A":       8.81,
        "Voc_V":       45.7,
        "Isc_A":       9.39,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Polycristallin",
        "puissance_W": 330.0,
        "tension_V":   36.0,
        "Vmp_V":       37.1,
        "Imp_A":       8.89,
        "Voc_V":       45.7,
        "Isc_A":       9.47,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Monocristallin",
        "puissance_W": 290.0,
        "tension_V":   24.0,
        "Vmp_V":       31.9,
        "Imp_A":       9.6,
        "Voc_V":       38.9,
        "Isc_A":       9.6,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Monocristallin",
        "puissance_W": 295.0,
        "tension_V":   24.0,
        "Vmp_V":       32.0,
        "Imp_A":       9.16,
        "Voc_V":       39.1,
        "Isc_A":       9.69,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Monocristallin",
        "puissance_W": 300.0,
        "tension_V":   24.0,
        "Vmp_V":       32.3,
        "Imp_A":       9.29,
        "Voc_V":       39.2,
        "Isc_A":       9.82,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Monocristallin",
        "puissance_W": 335.0,
        "tension_V":   36.0,
        "Vmp_V":       36.3,
        "Imp_A":       9.23,
        "Voc_V":       44.2,
        "Isc_A":       9.77,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Monocristallin",
        "puissance_W": 340.0,
        "tension_V":   36.0,
        "Vmp_V":       36.5,
        "Imp_A":       9.34,
        "Voc_V":       44.4,
        "Isc_A":       9.88,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Monocristallin",
        "puissance_W": 345.0,
        "tension_V":   24.0,
        "Vmp_V":       36.7,
        "Imp_A":       9.4,
        "Voc_V":       44.6,
        "Isc_A":       9.94,
        "rendement":   0.006,
    },
    {
        "marque":      "Mercury",
        "type":        "Monocristallin",
        "puissance_W": 350.0,
        "tension_V":   24.0,
        "Vmp_V":       37.0,
        "Imp_A":       9.46,
        "Voc_V":       45.0,
        "Isc_A":       9.99,
        "rendement":   0.006,
    },
    {
        "marque":      "Jinko Solar",
        "type":        "Polycristallin",
        "puissance_W": 245.0,
        "tension_V":   24.0,
        "Vmp_V":       30.1,
        "Imp_A":       8.14,
        "Voc_V":       37.5,
        "Isc_A":       8.76,
        "rendement":   0.006,
    },
    {
        "marque":      "Jinko Solar",
        "type":        "Polycristallin",
        "puissance_W": 250.0,
        "tension_V":   24.0,
        "Vmp_V":       30.5,
        "Imp_A":       8.2,
        "Voc_V":       37.7,
        "Isc_A":       8.85,
        "rendement":   0.006,
    },
    {
        "marque":      "Jinko Solar",
        "type":        "Polycristallin",
        "puissance_W": 255.0,
        "tension_V":   24.0,
        "Vmp_V":       30.8,
        "Imp_A":       8.28,
        "Voc_V":       38.0,
        "Isc_A":       8.92,
        "rendement":   0.006,
    },
    {
        "marque":      "Jinko Solar",
        "type":        "Polycristallin",
        "puissance_W": 260.0,
        "tension_V":   24.0,
        "Vmp_V":       31.1,
        "Imp_A":       8.37,
        "Voc_V":       38.1,
        "Isc_A":       8.98,
        "rendement":   0.006,
    },
    {
        "marque":      "Jinko Solar",
        "type":        "Polycristallin",
        "puissance_W": 265.0,
        "tension_V":   24.0,
        "Vmp_V":       31.4,
        "Imp_A":       8.44,
        "Voc_V":       38.6,
        "Isc_A":       9.03,
        "rendement":   0.006,
    },
    {
        "marque":      "PhotoWatt",
        "type":        "Polycristallin",
        "puissance_W": 240.0,
        "tension_V":   24.0,
        "Vmp_V":       29.9,
        "Imp_A":       8.03,
        "Voc_V":       37.0,
        "Isc_A":       8.59,
        "rendement":   0.006,
    },
    {
        "marque":      "PhotoWatt",
        "type":        "Polycristallin",
        "puissance_W": 245.0,
        "tension_V":   24.0,
        "Vmp_V":       30.0,
        "Imp_A":       8.17,
        "Voc_V":       37.1,
        "Isc_A":       8.74,
        "rendement":   0.006,
    },
    {
        "marque":      "PhotoWatt",
        "type":        "Polycristallin",
        "puissance_W": 250.0,
        "tension_V":   24.0,
        "Vmp_V":       30.1,
        "Imp_A":       8.3,
        "Voc_V":       37.7,
        "Isc_A":       8.87,
        "rendement":   0.006,
    },
    {
        "marque":      "PhotoWatt",
        "type":        "Polycristallin",
        "puissance_W": 255.0,
        "tension_V":   24.0,
        "Vmp_V":       30.5,
        "Imp_A":       8.4,
        "Voc_V":       37.7,
        "Isc_A":       8.9,
        "rendement":   0.006,
    },
    {
        "marque":      "Resun Solar",
        "type":        "Monocristallin",
        "puissance_W": 250.0,
        "tension_V":   24.0,
        "Vmp_V":       30.5,
        "Imp_A":       8.2,
        "Voc_V":       36.6,
        "Isc_A":       9.01,
        "rendement":   0.006,
    },
    {
        "marque":      "Resun Solar",
        "type":        "Monocristallin",
        "puissance_W": 255.0,
        "tension_V":   24.0,
        "Vmp_V":       30.7,
        "Imp_A":       8.31,
        "Voc_V":       36.8,
        "Isc_A":       9.14,
        "rendement":   0.006,
    },
    {
        "marque":      "Resun Solar",
        "type":        "Monocristallin",
        "puissance_W": 260.0,
        "tension_V":   24.0,
        "Vmp_V":       30.9,
        "Imp_A":       8.41,
        "Voc_V":       37.1,
        "Isc_A":       9.25,
        "rendement":   0.006,
    },
    {
        "marque":      "Resun Solar",
        "type":        "Monocristallin",
        "puissance_W": 265.0,
        "tension_V":   24.0,
        "Vmp_V":       31.1,
        "Imp_A":       8.52,
        "Voc_V":       37.3,
        "Isc_A":       9.37,
        "rendement":   0.006,
    },
    {
        "marque":      "Resun Solar",
        "type":        "Monocristallin",
        "puissance_W": 270.0,
        "tension_V":   24.0,
        "Vmp_V":       31.2,
        "Imp_A":       8.65,
        "Voc_V":       37.4,
        "Isc_A":       9.52,
        "rendement":   0.006,
    },
    {
        "marque":      "Resun Solar",
        "type":        "Monocristallin",
        "puissance_W": 275.0,
        "tension_V":   24.0,
        "Vmp_V":       31.3,
        "Imp_A":       8.79,
        "Voc_V":       37.6,
        "Isc_A":       9.66,
        "rendement":   0.006,
    },
    {
        "marque":      "Resun Solar",
        "type":        "Monocristallin",
        "puissance_W": 280.0,
        "tension_V":   24.0,
        "Vmp_V":       31.7,
        "Imp_A":       8.84,
        "Voc_V":       38.4,
        "Isc_A":       9.42,
        "rendement":   0.006,
    },
    {
        "marque":      "Centro Solar",
        "type":        "Monocristallin",
        "puissance_W": 325.0,
        "tension_V":   24.0,
        "Vmp_V":       37.22,
        "Imp_A":       8.74,
        "Voc_V":       45.65,
        "Isc_A":       9.24,
        "rendement":   0.006,
    },
    {
        "marque":      "Centro Solar",
        "type":        "Monocristallin",
        "puissance_W": 330.0,
        "tension_V":   24.0,
        "Vmp_V":       37.38,
        "Imp_A":       8.85,
        "Voc_V":       45.92,
        "Isc_A":       9.32,
        "rendement":   0.006,
    },
    {
        "marque":      "Centro Solar",
        "type":        "Monocristallin",
        "puissance_W": 335.0,
        "tension_V":   24.0,
        "Vmp_V":       37.47,
        "Imp_A":       8.96,
        "Voc_V":       46.04,
        "Isc_A":       9.41,
        "rendement":   0.006,
    },
    {
        "marque":      "Sunlink PV",
        "type":        "Polycristallin",
        "puissance_W": 150.0,
        "tension_V":   12.0,
        "Vmp_V":       17.2,
        "Imp_A":       8.72,
        "Voc_V":       21.6,
        "Isc_A":       9.25,
        "rendement":   0.006,
    },
    {
        "marque":      "Sunlink PV",
        "type":        "Polycristallin",
        "puissance_W": 255.0,
        "tension_V":   24.0,
        "Vmp_V":       30.7,
        "Imp_A":       8.3,
        "Voc_V":       37.3,
        "Isc_A":       8.9,
        "rendement":   0.006,
    },
    {
        "marque":      "Sunlink PV",
        "type":        "Polycristallin",
        "puissance_W": 260.0,
        "tension_V":   24.0,
        "Vmp_V":       30.9,
        "Imp_A":       8.41,
        "Voc_V":       37.5,
        "Isc_A":       9.01,
        "rendement":   0.006,
    },
    {
        "marque":      "Sunlink PV",
        "type":        "Polycristallin",
        "puissance_W": 265.0,
        "tension_V":   24.0,
        "Vmp_V":       31.1,
        "Imp_A":       8.53,
        "Voc_V":       37.5,
        "Isc_A":       9.12,
        "rendement":   0.006,
    },
    {
        "marque":      "Sunlink PV",
        "type":        "Polycristallin",
        "puissance_W": 270.0,
        "tension_V":   24.0,
        "Vmp_V":       31.3,
        "Imp_A":       8.63,
        "Voc_V":       37.9,
        "Isc_A":       9.23,
        "rendement":   0.006,
    },
    {
        "marque":      "Sunlink PV",
        "type":        "Polycristallin",
        "puissance_W": 275.0,
        "tension_V":   24.0,
        "Vmp_V":       31.5,
        "Imp_A":       8.74,
        "Voc_V":       30.1,
        "Isc_A":       9.23,
        "rendement":   0.006,
    },
]


# ============================================================
# BASE DE DONNÉES DES BATTERIES
# ============================================================

BATTERIES = [
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 240.0,
        "tension_V":   6.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 8.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 14.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 22.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 38.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 60.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 66.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 90.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 110.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 130.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 165.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 220.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 240.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 60.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 66.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 90.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 110.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 130.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 165.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 220.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 265.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 2320.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 3540.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Tesvolt",
        "type":        "Lithium -ion",
        "capacite_Ah": 282.0,
        "tension_V":   48.0,
        "rendement":   0.9,
        "DoD":         0.8,
    },
    {
        "marque":      "Tesvolt",
        "type":        "Lithium -ion",
        "capacite_Ah": 376.0,
        "tension_V":   48.0,
        "rendement":   0.9,
        "DoD":         0.8,
    },
    {
        "marque":      "Tesvolt",
        "type":        "Lithium -ion",
        "capacite_Ah": 470.0,
        "tension_V":   48.0,
        "rendement":   0.9,
        "DoD":         0.8,
    },
    {
        "marque":      "Tesvolt",
        "type":        "Lithium -ion",
        "capacite_Ah": 564.0,
        "tension_V":   48.0,
        "rendement":   0.9,
        "DoD":         0.8,
    },
    {
        "marque":      "Tesvolt",
        "type":        "Lithium -ion",
        "capacite_Ah": 658.0,
        "tension_V":   48.0,
        "rendement":   0.9,
        "DoD":         0.8,
    },
    {
        "marque":      "Tesvolt",
        "type":        "Lithium -ion",
        "capacite_Ah": 752.0,
        "tension_V":   48.0,
        "rendement":   0.9,
        "DoD":         0.8,
    },
    {
        "marque":      "Tesvolt",
        "type":        "Lithium -ion",
        "capacite_Ah": 846.0,
        "tension_V":   48.0,
        "rendement":   0.9,
        "DoD":         0.8,
    },
    {
        "marque":      "Tesvolt",
        "type":        "Lithium -ion",
        "capacite_Ah": 940.0,
        "tension_V":   48.0,
        "rendement":   0.9,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 1750.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 2740.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 3000.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 3750.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 4710.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 121.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 243.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 610.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 202.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 404.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "BAE",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 506.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 200.0,
        "tension_V":   6.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 80.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 115.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 120.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 140.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 160.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 210.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 215.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 220.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 240.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 260.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 100.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 110.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 200.0,
        "tension_V":   12.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 1000.0,
        "tension_V":   2.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 2290.0,
        "tension_V":   2.0,
        "rendement":   0.85,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 80.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 130.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 170.0,
        "tension_V":   6.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 200.0,
        "tension_V":   6.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 220.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 490.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 520.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 910.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 1200.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 1500.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 2000.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 2500.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 3000.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 3330.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Hoppecke",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 202.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Moll",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 335.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Moll",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 598.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Moll",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 2120.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Moll",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 2320.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Moll",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 305.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Moll",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 400.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Moll",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 610.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Moll",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 1570.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Moll",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 2023.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Moll",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 3050.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Rolls",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 220.0,
        "tension_V":   6.0,
        "rendement":   0.97,
        "DoD":         0.8,
    },
    {
        "marque":      "Rolls",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 500.0,
        "tension_V":   2.0,
        "rendement":   0.97,
        "DoD":         0.8,
    },
    {
        "marque":      "Rolls",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 1000.0,
        "tension_V":   2.0,
        "rendement":   0.97,
        "DoD":         0.8,
    },
    {
        "marque":      "Rolls",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 3000.0,
        "tension_V":   2.0,
        "rendement":   0.97,
        "DoD":         0.8,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 415.0,
        "tension_V":   6.0,
        "rendement":   0.85,
        "DoD":         0.91,
    },
    {
        "marque":      "Fullriver",
        "type":        "Plomb-acide AGM",
        "capacite_Ah": 224.0,
        "tension_V":   6.0,
        "rendement":   0.85,
        "DoD":         0.91,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Lithium -ion",
        "capacite_Ah": 60.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.95,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Lithium -ion",
        "capacite_Ah": 90.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.95,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Lithium -ion",
        "capacite_Ah": 180.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.95,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Lithium -ion",
        "capacite_Ah": 160.0,
        "tension_V":   24.0,
        "rendement":   0.8,
        "DoD":         0.95,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Lithium -ion",
        "capacite_Ah": 200.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.95,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 910.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 1210.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 1520.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 1830.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 2280.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 3040.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 3800.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Victron Energy",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 4560.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 40.0,
        "tension_V":   40.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 65.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 70.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 75.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 100.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 150.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 180.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 200.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 210.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 250.0,
        "tension_V":   12.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 500.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 1000.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 1500.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
    {
        "marque":      "Yongda power",
        "type":        "Plomb-acide GEL",
        "capacite_Ah": 2930.0,
        "tension_V":   2.0,
        "rendement":   0.8,
        "DoD":         0.8,
    },
]


# ============================================================
# BASE DE DONNÉES DES RÉGULATEURS MPPT
# ============================================================

REGULATEURS_MPPT = [
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 75/10",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 10.0,
        "isc_max_A":   13.0,
        "voc_max_V":   75.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 75/10",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 10.0,
        "isc_max_A":   13.0,
        "voc_max_V":   75.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 75/15",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 15.0,
        "isc_max_A":   15.0,
        "voc_max_V":   75.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 75/15",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 15.0,
        "isc_max_A":   15.0,
        "voc_max_V":   75.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 100/15",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 15.0,
        "isc_max_A":   15.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 100/15",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 15.0,
        "isc_max_A":   15.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 100/20",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   20.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 100/20",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   20.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 100/20",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   20.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 100/30",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 30.0,
        "isc_max_A":   35.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 100/30",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 30.0,
        "isc_max_A":   35.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 100/50",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 50.0,
        "isc_max_A":   60.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 100/50",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 50.0,
        "isc_max_A":   60.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/35",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 35.0,
        "isc_max_A":   40.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/35",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 35.0,
        "isc_max_A":   40.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/35",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 35.0,
        "isc_max_A":   40.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/45",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 45.0,
        "isc_max_A":   50.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/45",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 45.0,
        "isc_max_A":   50.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/45",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 45.0,
        "isc_max_A":   50.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/60",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 60.0,
        "isc_max_A":   50.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/60",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 60.0,
        "isc_max_A":   50.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/60",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 60.0,
        "isc_max_A":   50.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/70",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 70.0,
        "isc_max_A":   50.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/70",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 70.0,
        "isc_max_A":   50.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/70",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 70.0,
        "isc_max_A":   50.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/70",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 70.0,
        "isc_max_A":   35.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/70",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 70.0,
        "isc_max_A":   35.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/70",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 70.0,
        "isc_max_A":   35.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/60",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 60.0,
        "isc_max_A":   35.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/60",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 60.0,
        "isc_max_A":   35.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/60",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 60.0,
        "isc_max_A":   35.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/85",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 85.0,
        "isc_max_A":   70.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/85",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 85.0,
        "isc_max_A":   70.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/85",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 85.0,
        "isc_max_A":   70.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/100",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 100.0,
        "isc_max_A":   70.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/100",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 100.0,
        "isc_max_A":   70.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 150/100",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 100.0,
        "isc_max_A":   70.0,
        "voc_max_V":   145.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/85",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 85.0,
        "isc_max_A":   70.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/85",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 85.0,
        "isc_max_A":   70.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/85",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 85.0,
        "isc_max_A":   70.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/100",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 100.0,
        "isc_max_A":   70.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/100",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 100.0,
        "isc_max_A":   70.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 250/100",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 100.0,
        "isc_max_A":   70.0,
        "voc_max_V":   245.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 450/100",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 100.0,
        "isc_max_A":   20.0,
        "voc_max_V":   450.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "SmartSolar MPPT 450/200",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 200.0,
        "isc_max_A":   20.0,
        "voc_max_V":   450.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix MPPT 3020 (100V)",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   30.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix MPPT 3020 (100V)",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   30.0,
        "voc_max_V":   100.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix MPPT 5020",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   50.0,
        "voc_max_V":   150.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix MPPT 5020",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   50.0,
        "voc_max_V":   150.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix MPPT 5020",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   50.0,
        "voc_max_V":   150.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix MPPT 5020 (150Voc)",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   50.0,
        "voc_max_V":   17.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix MPPT 5020 (150Voc)",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   50.0,
        "voc_max_V":   64.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix MPPT 5020 (150Voc)",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 20.0,
        "isc_max_A":   50.0,
        "voc_max_V":   150.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "TS MPPT 45",
        "type":        "MPPT",
        "tension_bat_V": 12.0,
        "courant_nom_A": 45.0,
        "isc_max_A":   60.0,
        "voc_max_V":   150.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "TS MPPT 45",
        "type":        "MPPT",
        "tension_bat_V": 24.0,
        "courant_nom_A": 45.0,
        "isc_max_A":   60.0,
        "voc_max_V":   150.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "TS MPPT 45",
        "type":        "MPPT",
        "tension_bat_V": 36.0,
        "courant_nom_A": 45.0,
        "isc_max_A":   60.0,
        "voc_max_V":   150.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "TS MPPT 45",
        "type":        "MPPT",
        "tension_bat_V": 48.0,
        "courant_nom_A": 45.0,
        "isc_max_A":   60.0,
        "voc_max_V":   150.0,
    },
]


# ============================================================
# BASE DE DONNÉES DES RÉGULATEURS PWM
# ============================================================

REGULATEURS_PWM = [
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-PRO 12/24-5",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 5.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-PRO 12/24-5",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 5.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-PRO 12/24-10",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-PRO 12/24-10",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-PRO 12/24-20",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-PRO 12/24-20",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-PRO 12/24-30",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 30.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-PRO 12/24-30",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 30.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 48-10",
        "type":        "PWM",
        "tension_bat_V": 48.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 48-20",
        "type":        "PWM",
        "tension_bat_V": 48.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 48-30",
        "type":        "PWM",
        "tension_bat_V": 48.0,
        "courant_nom_A": 30.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 12/24-5",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 5.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 12/24-5",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 5.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 12/24-10",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 12/24-10",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 12/24-20",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 12/24-20",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 12/24-30",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 30.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-LIGHT 12/24-30",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 30.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-DUO LCD-USB 12/24-20",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "VICTRON",
        "designation": "BLUE SOLAR PWM-DUO LCD-USB 12/24-20",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "STECA",
        "designation": "PR 3030",
        "type":        "PWM",
        "tension_bat_V": 14.0,
        "courant_nom_A": 30.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solsum 0606",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 6.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solsum 0606",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 6.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solsum 8,8F",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 8.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solsum 8,8F",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 8.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solsum 10,10F",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solsum 10,10F",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "STECA",
        "designation": "STECA PRS1010",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "STECA",
        "designation": "STECA PRS1010",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "STECA",
        "designation": "STECA PRS1515",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 15.0,
    },
    {
        "marque":      "STECA",
        "designation": "STECA PRS1515",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 15.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solsum 4040",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 40.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solsum 4040",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 40.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix PRS3030",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 30.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix PRS3030",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 30.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solsum 2525",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 25.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solsum 2525",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 25.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix PRS2020",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix PRS2020",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "STECA",
        "designation": "STECA PR1010",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "STECA",
        "designation": "STECA PR1010",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 10.0,
    },
    {
        "marque":      "STECA",
        "designation": "STECA PR1515",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 15.0,
    },
    {
        "marque":      "STECA",
        "designation": "STECA PR1515",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 15.0,
    },
    {
        "marque":      "STECA",
        "designation": "STECA PR2020",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "STECA",
        "designation": "STECA PR2020",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix 2525",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 25.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix 2525",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 25.0,
    },
    {
        "marque":      "STECA",
        "designation": "Tarom 4545-48",
        "type":        "PWM",
        "tension_bat_V": 48.0,
        "courant_nom_A": 45.0,
    },
    {
        "marque":      "STECA",
        "designation": "Tarom 4545",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 45.0,
    },
    {
        "marque":      "STECA",
        "designation": "Tarom 4545",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 45.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix 4040",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 40.0,
    },
    {
        "marque":      "STECA",
        "designation": "Solarix 4040",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 40.0,
    },
    {
        "marque":      "STECA",
        "designation": "PR3030",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 30.0,
    },
    {
        "marque":      "STECA",
        "designation": "PR3030",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 30.0,
    },
    {
        "marque":      "STECA",
        "designation": "étanche PR 2020",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "STECA",
        "designation": "étanche PR 2020",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 20.0,
    },
    {
        "marque":      "STECA",
        "designation": "Tarom 4140 - LCD",
        "type":        "PWM",
        "tension_bat_V": 48.0,
        "courant_nom_A": 140.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "SunSaver Duo SSD 25",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 25.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "SunSaver DUO + LCD SSD-25",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 25.0,
    },
    {
        "marque":      "TENESOL",
        "designation": "ENER15",
        "type":        "PWM",
        "tension_bat_V": 48.0,
        "courant_nom_A": 15.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "TRISTAR 45A",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 45.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "TRISTAR 45A",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 45.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "TRISTAR 45A",
        "type":        "PWM",
        "tension_bat_V": 48.0,
        "courant_nom_A": 45.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "TRISTAR 60A",
        "type":        "PWM",
        "tension_bat_V": 12.0,
        "courant_nom_A": 60.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "TRISTAR 60A",
        "type":        "PWM",
        "tension_bat_V": 24.0,
        "courant_nom_A": 60.0,
    },
    {
        "marque":      "MORNINGSTAR",
        "designation": "TRISTAR 60A",
        "type":        "PWM",
        "tension_bat_V": 48.0,
        "courant_nom_A": 45.0,
    },
]


# ============================================================
# BASE DE DONNÉES DES ONDULEURS
# ============================================================

ONDULEURS = [
    {
        "marque":            "Victron Energy",
        "designation":       "Convertisseur Phonix Compact",
        "puissance_VA":      "1200VA-2000VA",
        "tension_entree_V":  "12/24V",
    },
    {
        "marque":            "Victron Energy",
        "designation":       "Phoenix Inverter",
        "puissance_VA":      "3000VA-5000VA",
        "tension_entree_V":  "48V",
    },
    {
        "marque":            "Victron Energy",
        "designation":       "Convertisseur Phoenix Smaet",
        "puissance_VA":      "1600VA-5000VA",
        "tension_entree_V":  "12/24/48V",
    },
    {
        "marque":            "Victron Energy",
        "designation":       "Sun Inverter",
        "puissance_VA":      "250VA",
        "tension_entree_V":  "12/24V",
    },
    {
        "marque":            "Victron Energy",
        "designation":       "Convertisseur Phoenix-VE.Direct",
        "puissance_VA":      "250VA-1200VA",
        "tension_entree_V":  "N/A",
    },
    {
        "marque":            "Victron Energy",
        "designation":       "Convertisseur RS Smart",
        "puissance_VA":      "6000VA",
        "tension_entree_V":  "N/A",
    },
    {
        "marque":            "Victron Energy",
        "designation":       "Convertisseur RS Smart Solar",
        "puissance_VA":      "6000VA",
        "tension_entree_V":  "N/A",
    },
]


# ============================================================
# FONCTIONS DE RECHERCHE
# ============================================================

def get_marques_panneaux():
    marques = []
    for p in PANNEAUX:
        if p["marque"] not in marques:
            marques.append(p["marque"])
    return sorted(marques)

def get_modeles_panneaux(marque):
    return [p for p in PANNEAUX if p["marque"] == marque]

def get_marques_batteries():
    marques = []
    for b in BATTERIES:
        if b["marque"] not in marques:
            marques.append(b["marque"])
    return sorted(marques)

def get_modeles_batteries(marque):
    return [b for b in BATTERIES if b["marque"] == marque]

def get_marques_regulateurs():
    marques = []
    for r in REGULATEURS_MPPT + REGULATEURS_PWM:
        if r["marque"] not in marques:
            marques.append(r["marque"])
    return sorted(marques)

def get_regulateurs(marque, type_reg=None):
    tous = REGULATEURS_MPPT + REGULATEURS_PWM
    if type_reg:
        return [r for r in tous if r["marque"] == marque and r["type"] == type_reg]
    return [r for r in tous if r["marque"] == marque]

def get_onduleurs(marque=None):
    if marque:
        return [o for o in ONDULEURS if o["marque"] == marque]
    return ONDULEURS